version: "3.2"

volumes:
  data:
    external:
      name: ${TARGET_VOLUME} 

services:
  backup:
    image: busybox:latest
    volumes:
      - data:/target
      - ../${BACKUP_DIR}:/dst
    command: "/bin/tar -C /target -zcvf /dst/${TARGET_VOLUME}_${TAG}.tar.gz ./"