version: "3.2"

volumes:
  data:
    external:
      name: ${TARGET_VOLUME}

services:
  restore:
    image: busybox:latest
    volumes:
      - data:/target
      - ../backup_data:/src
    command: /bin/sh -c "/bin/rm -rf /target/* && /bin/tar -C /target -zxvf /src/${BACKUP_FILE}"